# Generated by Django 5.0.1 on 2024-05-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movieclub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("movie_title", models.CharField(max_length=255)),
                ("poster", models.ImageField(upload_to="image/")),
                ("description", models.CharField(max_length=255)),
                ("release_date", models.DateField()),
                ("cast", models.CharField(max_length=1000)),
                ("category", models.CharField(max_length=200)),
                ("youtube_trailer_link", models.URLField()),
            ],
        ),
    ]
